package com.karaoke.service.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2016-10-23T13:09:18.417-05:00
 * Generated source version: 3.1.8
 * 
 */
@WebService(targetNamespace = "http://localhost:8080/", name = "CancionService")
@XmlSeeAlso({ObjectFactory.class})
public interface CancionService {

    @WebMethod
    @RequestWrapper(localName = "crearCancion", targetNamespace = "http://localhost:8080/", className = "com.karaoke.service.client.CrearCancion")
    @ResponseWrapper(localName = "crearCancionResponse", targetNamespace = "http://localhost:8080/", className = "com.karaoke.service.client.CrearCancionResponse")
    public void crearCancion(
        @WebParam(name = "arg0", targetNamespace = "")
        com.karaoke.service.client.Cancion arg0
    );
}
