package com.karaoke.service.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2016-10-23T13:09:18.421-05:00
 * Generated source version: 3.1.8
 * 
 */
@WebServiceClient(name = "CancionServiceImplService", 
                  wsdlLocation = "http://localhost:8080/KaraokeService/services/CancionService?wsdl",
                  targetNamespace = "http://localhost:8080/") 
public class CancionServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://localhost:8080/", "CancionServiceImplService");
    public final static QName CancionServiceImplPort = new QName("http://localhost:8080/", "CancionServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/KaraokeService/services/CancionService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CancionServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/KaraokeService/services/CancionService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CancionServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CancionServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CancionServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public CancionServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CancionServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CancionServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns CancionService
     */
    @WebEndpoint(name = "CancionServiceImplPort")
    public CancionService getCancionServiceImplPort() {
        return super.getPort(CancionServiceImplPort, CancionService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CancionService
     */
    @WebEndpoint(name = "CancionServiceImplPort")
    public CancionService getCancionServiceImplPort(WebServiceFeature... features) {
        return super.getPort(CancionServiceImplPort, CancionService.class, features);
    }

}
