
package com.karaoke.service.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2016-10-23T13:09:18.365-05:00
 * Generated source version: 3.1.8
 * 
 */
public final class CancionService_CancionServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://localhost:8080/", "CancionServiceImplService");

    private CancionService_CancionServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = CancionServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        CancionServiceImplService ss = new CancionServiceImplService(wsdlURL, SERVICE_NAME);
        CancionService port = ss.getCancionServiceImplPort();  
        
        {
        System.out.println("Invoking crearCancion...");
        com.karaoke.service.client.Cancion _crearCancion_arg0 = new com.karaoke.service.client.Cancion();
        _crearCancion_arg0.setAutor("Autor392125363");
        _crearCancion_arg0.setEstado(Integer.valueOf(-1132337297));
        _crearCancion_arg0.setGenero("Genero-402900343");
        _crearCancion_arg0.setId(Long.valueOf(-5430449757828433755l));
        _crearCancion_arg0.setNombre("Nombre1229384594");
        java.util.List<com.karaoke.service.client.Pedido> _crearCancion_arg0Pedidos = new java.util.ArrayList<com.karaoke.service.client.Pedido>();
        com.karaoke.service.client.Pedido _crearCancion_arg0PedidosVal1 = new com.karaoke.service.client.Pedido();
        com.karaoke.service.client.Cancion _crearCancion_arg0PedidosVal1Cancion = new com.karaoke.service.client.Cancion();
        _crearCancion_arg0PedidosVal1Cancion.setAutor("Autor-1107698199");
        _crearCancion_arg0PedidosVal1Cancion.setEstado(Integer.valueOf(-711872547));
        _crearCancion_arg0PedidosVal1Cancion.setGenero("Genero-416961848");
        _crearCancion_arg0PedidosVal1Cancion.setId(Long.valueOf(785695182210545699l));
        _crearCancion_arg0PedidosVal1Cancion.setNombre("Nombre619009546");
        java.util.List<com.karaoke.service.client.Pedido> _crearCancion_arg0PedidosVal1CancionPedidos = new java.util.ArrayList<com.karaoke.service.client.Pedido>();
        _crearCancion_arg0PedidosVal1Cancion.getPedidos().addAll(_crearCancion_arg0PedidosVal1CancionPedidos);
        _crearCancion_arg0PedidosVal1.setCancion(_crearCancion_arg0PedidosVal1Cancion);
        _crearCancion_arg0PedidosVal1.setDispositivoId("DispositivoId-1316130450");
        _crearCancion_arg0PedidosVal1.setEstado(Integer.valueOf(641930199));
        _crearCancion_arg0PedidosVal1.setFechaHora(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2016-10-23T13:09:18.404-05:00"));
        _crearCancion_arg0PedidosVal1.setId(Long.valueOf(1524170287821386479l));
        _crearCancion_arg0Pedidos.add(_crearCancion_arg0PedidosVal1);
        _crearCancion_arg0.getPedidos().addAll(_crearCancion_arg0Pedidos);
        port.crearCancion(_crearCancion_arg0);


        }

        System.exit(0);
    }

}
