
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.karaoke.service.client;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2016-10-23T13:09:18.410-05:00
 * Generated source version: 3.1.8
 * 
 */

@javax.jws.WebService(
                      serviceName = "CancionServiceImplService",
                      portName = "CancionServiceImplPort",
                      targetNamespace = "http://localhost:8080/",
                      wsdlLocation = "http://localhost:8080/KaraokeService/services/CancionService?wsdl",
                      endpointInterface = "com.karaoke.service.client.CancionService")
                      
public class CancionServiceImplPortImpl implements CancionService {

    private static final Logger LOG = Logger.getLogger(CancionServiceImplPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.karaoke.service.client.CancionService#crearCancion(com.karaoke.service.client.Cancion arg0)*
     */
    public void crearCancion(com.karaoke.service.client.Cancion arg0) { 
        LOG.info("Executing operation crearCancion");
        System.out.println(arg0);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
