
package com.karaoke.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.8
 * Sun Oct 23 11:06:09 COT 2016
 * Generated source version: 3.1.8
 */

@XmlRootElement(name = "crearCancion", namespace = "http://localhost:8080/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "crearCancion", namespace = "http://localhost:8080/")

public class CrearCancion {

    @XmlElement(name = "arg0")
    private com.karaoke.domain.entity.Cancion arg0;

    public com.karaoke.domain.entity.Cancion getArg0() {
        return this.arg0;
    }

    public void setArg0(com.karaoke.domain.entity.Cancion newArg0)  {
        this.arg0 = newArg0;
    }

}

