
package com.karaoke.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.8
 * Sun Oct 23 11:06:09 COT 2016
 * Generated source version: 3.1.8
 */

@XmlRootElement(name = "crearCancionResponse", namespace = "http://localhost:8080/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "crearCancionResponse", namespace = "http://localhost:8080/")

public class CrearCancionResponse {


}

